import { nanoid } from 'nanoid';

export const employees = [
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    dateOfEmployment: new Date(2018, 2, 14),
    dateOfBirth: new Date(1990, 6, 22),
    phone: '+1-202-555-0143',
    email: 'alice.johnson@example.com',
    department: 'Engineering',
    position: 'Engineer',
  },
  {
    firstName: 'Bob',
    lastName: 'Smith',
    dateOfEmployment: new Date(2015, 10, 5),
    dateOfBirth: new Date(1985, 1, 13),
    phone: '+1-202-555-0178',
    email: 'bob.smith@example.com',
    department: 'HR',
    position: 'Manager',
  },
  {
    firstName: 'Carol',
    lastName: 'Davis',
    dateOfEmployment: new Date(2020, 6, 20),
    dateOfBirth: new Date(1992, 9, 5),
    phone: '+1-202-555-0199',
    email: 'carol.davis@example.com',
    department: 'Marketing',
    position: 'Coordinator',
  },
  {
    firstName: 'David',
    lastName: 'Martinez',
    dateOfEmployment: new Date(2017, 8, 12),
    dateOfBirth: new Date(1988, 3, 18),
    phone: '+1-202-555-0123',
    email: 'david.martinez@example.com',
    department: 'Finance',
    position: 'Analyst',
  },
  {
    firstName: 'Emma',
    lastName: 'Brown',
    dateOfEmployment: new Date(2019, 4, 1),
    dateOfBirth: new Date(1995, 0, 29),
    phone: '+1-202-555-0167',
    email: 'emma.brown@example.com',
    department: 'Support',
    position: 'Specialist',
  },
  {
    firstName: 'Frank',
    lastName: 'Wilson',
    dateOfEmployment: new Date(2016, 11, 18),
    dateOfBirth: new Date(1983, 7, 2),
    phone: '+1-202-555-0110',
    email: 'frank.wilson@example.com',
    department: 'Engineering',
    position: 'Manager',
  },
  {
    firstName: 'Grace',
    lastName: 'Lee',
    dateOfEmployment: new Date(2018, 7, 22),
    dateOfBirth: new Date(1991, 2, 15),
    phone: '+1-202-555-0155',
    email: 'grace.lee@example.com',
    department: 'HR',
    position: 'Coordinator',
  },
  {
    firstName: 'Henry',
    lastName: 'Garcia',
    dateOfEmployment: new Date(2021, 1, 10),
    dateOfBirth: new Date(1996, 8, 8),
    phone: '+1-202-555-0182',
    email: 'henry.garcia@example.com',
    department: 'Sales',
    position: 'Executive',
  },
  {
    firstName: 'Isabella',
    lastName: 'Clark',
    dateOfEmployment: new Date(2017, 5, 30),
    dateOfBirth: new Date(1990, 11, 11),
    phone: '+1-202-555-0134',
    email: 'isabella.clark@example.com',
    department: 'Marketing',
    position: 'Specialist',
  },
  {
    firstName: 'Jack',
    lastName: 'Lewis',
    dateOfEmployment: new Date(2014, 9, 8),
    dateOfBirth: new Date(1984, 6, 19),
    phone: '+1-202-555-0190',
    email: 'jack.lewis@example.com',
    department: 'Finance',
    position: 'Analyst',
  },
  {
    firstName: 'Karen',
    lastName: 'Walker',
    dateOfEmployment: new Date(2020, 10, 15),
    dateOfBirth: new Date(1993, 4, 25),
    phone: '+1-202-555-0175',
    email: 'karen.walker@example.com',
    department: 'Support',
    position: 'Specialist',
  },
  {
    firstName: 'Leo',
    lastName: 'Hall',
    dateOfEmployment: new Date(2019, 2, 4),
    dateOfBirth: new Date(1989, 10, 3),
    phone: '+1-202-555-0140',
    email: 'leo.hall@example.com',
    department: 'Engineering',
    position: 'Engineer',
  },
  {
    firstName: 'Mia',
    lastName: 'Allen',
    dateOfEmployment: new Date(2016, 6, 12),
    dateOfBirth: new Date(1992, 1, 14),
    phone: '+1-202-555-0188',
    email: 'mia.allen@example.com',
    department: 'HR',
    position: 'Manager',
  },
  {
    firstName: 'Nathan',
    lastName: 'Young',
    dateOfEmployment: new Date(2018, 0, 22),
    dateOfBirth: new Date(1987, 5, 17),
    phone: '+1-202-555-0129',
    email: 'nathan.young@example.com',
    department: 'Sales',
    position: 'Executive',
  },
  {
    firstName: 'Olivia',
    lastName: 'Hernandez',
    dateOfEmployment: new Date(2021, 3, 5),
    dateOfBirth: new Date(1994, 9, 20),
    phone: '+1-202-555-0162',
    email: 'olivia.hernandez@example.com',
    department: 'Marketing',
    position: 'Coordinator',
  },
  {
    firstName: 'Peter',
    lastName: 'King',
    dateOfEmployment: new Date(2015, 8, 17),
    dateOfBirth: new Date(1985, 2, 29),
    phone: '+1-202-555-0115',
    email: 'peter.king@example.com',
    department: 'Finance',
    position: 'Analyst',
  },
  {
    firstName: 'Quinn',
    lastName: 'Wright',
    dateOfEmployment: new Date(2019, 11, 1),
    dateOfBirth: new Date(1991, 7, 12),
    phone: '+1-202-555-0193',
    email: 'quinn.wright@example.com',
    department: 'Support',
    position: 'Specialist',
  },
  {
    firstName: 'Rachel',
    lastName: 'Lopez',
    dateOfEmployment: new Date(2017, 4, 19),
    dateOfBirth: new Date(1988, 10, 27),
    phone: '+1-202-555-0148',
    email: 'rachel.lopez@example.com',
    department: 'Engineering',
    position: 'Engineer',
  },
  {
    firstName: 'Samuel',
    lastName: 'Hill',
    dateOfEmployment: new Date(2016, 2, 11),
    dateOfBirth: new Date(1986, 8, 9),
    phone: '+1-202-555-0139',
    email: 'samuel.hill@example.com',
    department: 'HR',
    position: 'Coordinator',
  },
  {
    firstName: 'Tina',
    lastName: 'Scott',
    dateOfEmployment: new Date(2018, 5, 25),
    dateOfBirth: new Date(1992, 0, 18),
    phone: '+1-202-555-0170',
    email: 'tina.scott@example.com',
    department: 'Sales',
    position: 'Executive',
  },
  {
    firstName: 'Ulysses',
    lastName: 'Green',
    dateOfEmployment: new Date(2019, 8, 8),
    dateOfBirth: new Date(1989, 4, 3),
    phone: '+1-202-555-0153',
    email: 'ulysses.green@example.com',
    department: 'Marketing',
    position: 'Coordinator',
  },
  {
    firstName: 'Victoria',
    lastName: 'Adams',
    dateOfEmployment: new Date(2020, 1, 20),
    dateOfBirth: new Date(1993, 11, 15),
    phone: '+1-202-555-0185',
    email: 'victoria.adams@example.com',
    department: 'Finance',
    position: 'Analyst',
  },
  {
    firstName: 'William',
    lastName: 'Baker',
    dateOfEmployment: new Date(2017, 10, 30),
    dateOfBirth: new Date(1987, 3, 7),
    phone: '+1-202-555-0169',
    email: 'william.baker@example.com',
    department: 'Support',
    position: 'Specialist',
  },
  {
    firstName: 'Xavier',
    lastName: 'Nelson',
    dateOfEmployment: new Date(2015, 7, 14),
    dateOfBirth: new Date(1984, 5, 23),
    phone: '+1-202-555-0122',
    email: 'xavier.nelson@example.com',
    department: 'Engineering',
    position: 'Engineer',
  },
  {
    firstName: 'Yara',
    lastName: 'Carter',
    dateOfEmployment: new Date(2021, 0, 10),
    dateOfBirth: new Date(1995, 6, 19),
    phone: '+1-202-555-0198',
    email: 'yara.carter@example.com',
    department: 'HR',
    position: 'Manager',
  },
  {
    firstName: 'Zachary',
    lastName: 'Mitchell',
    dateOfEmployment: new Date(2018, 3, 16),
    dateOfBirth: new Date(1990, 2, 11),
    phone: '+1-202-555-0151',
    email: 'zachary.mitchell@example.com',
    department: 'Sales',
    position: 'Executive',
  },
  {
    firstName: 'Anna',
    lastName: 'Perez',
    dateOfEmployment: new Date(2019, 6, 12),
    dateOfBirth: new Date(1992, 9, 9),
    phone: '+1-202-555-0135',
    email: 'anna.perez@example.com',
    department: 'Marketing',
    position: 'Specialist',
  },
  {
    firstName: 'Brian',
    lastName: 'Roberts',
    dateOfEmployment: new Date(2016, 8, 21),
    dateOfBirth: new Date(1986, 10, 2),
    phone: '+1-202-555-0181',
    email: 'brian.roberts@example.com',
    department: 'Finance',
    position: 'Analyst',
  },
  {
    firstName: 'Chloe',
    lastName: 'Turner',
    dateOfEmployment: new Date(2020, 4, 3),
    dateOfBirth: new Date(1994, 7, 22),
    phone: '+1-202-555-0147',
    email: 'chloe.turner@example.com',
    department: 'Support',
    position: 'Specialist',
  },
  {
    firstName: 'Daniel',
    lastName: 'Phillips',
    dateOfEmployment: new Date(2017, 1, 18),
    dateOfBirth: new Date(1988, 11, 4),
    phone: '+1-202-555-0165',
    email: 'daniel.phillips@example.com',
    department: 'Engineering',
    position: 'Engineer',
  },
  {
    firstName: 'Ella',
    lastName: 'Campbell',
    dateOfEmployment: new Date(2018, 9, 11),
    dateOfBirth: new Date(1991, 5, 16),
    phone: '+1-202-555-0127',
    email: 'ella.campbell@example.com',
    department: 'HR',
    position: 'Coordinator',
  },
  {
    firstName: 'Felix',
    lastName: 'Parker',
    dateOfEmployment: new Date(2019, 2, 23),
    dateOfBirth: new Date(1989, 8, 25),
    phone: '+1-202-555-0194',
    email: 'felix.parker@example.com',
    department: 'Sales',
    position: 'Executive',
  },
  {
    firstName: 'Gabriella',
    lastName: 'Evans',
    dateOfEmployment: new Date(2020, 5, 30),
    dateOfBirth: new Date(1993, 1, 10),
    phone: '+1-202-555-0172',
    email: 'gabriella.evans@example.com',
    department: 'Marketing',
    position: 'Coordinator',
  },
  {
    firstName: 'Harrison',
    lastName: 'Edwards',
    dateOfEmployment: new Date(2015, 10, 28),
    dateOfBirth: new Date(1985, 6, 7),
    phone: '+1-202-555-0113',
    email: 'harrison.edwards@example.com',
    department: 'Finance',
    position: 'Analyst',
  },
  {
    firstName: 'Ivy',
    lastName: 'Collins',
    dateOfEmployment: new Date(2016, 7, 15),
    dateOfBirth: new Date(1990, 11, 18),
    phone: '+1-202-555-0187',
    email: 'ivy.collins@example.com',
    department: 'Support',
    position: 'Specialist',
  },
  {
    firstName: 'James',
    lastName: 'Stewart',
    dateOfEmployment: new Date(2017, 4, 22),
    dateOfBirth: new Date(1987, 2, 28),
    phone: '+1-202-555-0137',
    email: 'james.stewart@example.com',
    department: 'Engineering',
    position: 'Engineer',
  },
  {
    firstName: 'Kylie',
    lastName: 'Sanchez',
    dateOfEmployment: new Date(2018, 0, 19),
    dateOfBirth: new Date(1992, 8, 12),
    phone: '+1-202-555-0158',
    email: 'kylie.sanchez@example.com',
    department: 'HR',
    position: 'Manager',
  },
  {
    firstName: 'Liam',
    lastName: 'Morris',
    dateOfEmployment: new Date(2019, 8, 6),
    dateOfBirth: new Date(1988, 3, 20),
    phone: '+1-202-555-0161',
    email: 'liam.morris@example.com',
    department: 'Sales',
    position: 'Executive',
  },
].map((employee) => ({
  ...employee,
  id: nanoid(),
}));
