name: CI - Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Run Tests & Lint
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Use correct Node version (change if needed)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run ESLint
      - name: Lint code
        run: npm run lint

      # 5️⃣ Run Vitest
      - name: Run tests
        run: npm run test -- --run

      # 6️⃣ (Optional) Upload test results (if you use coverage)
      - name: Upload coverage report
        if: success() && hashFiles('coverage/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
